/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgeRouteImport } from './routes/age'
import { Route as BasicRouteImport } from './routes/basic'
import { Route as BmiRouteImport } from './routes/bmi'
import { Route as DateRouteImport } from './routes/date'
import { Route as LoanRouteImport } from './routes/loan'
import { Route as MortgageRouteImport } from './routes/mortgage'
import { Route as PercentageRouteImport } from './routes/percentage'
import { Route as ScientificRouteImport } from './routes/scientific'
import { Route as TimeDurationRouteImport } from './routes/time-duration'
import { Route as TipRouteImport } from './routes/tip'
import { Route as UnitConverterRouteImport } from './routes/unit-converter'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgeRoute = AgeRouteImport.update({
  id: '/age',
  path: '/age',
  getParentRoute: () => rootRouteImport,
} as any)
const BasicRoute = BasicRouteImport.update({
  id: '/basic',
  path: '/basic',
  getParentRoute: () => rootRouteImport,
} as any)
const BmiRoute = BmiRouteImport.update({
  id: '/bmi',
  path: '/bmi',
  getParentRoute: () => rootRouteImport,
} as any)
const DateRoute = DateRouteImport.update({
  id: '/date',
  path: '/date',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanRoute = LoanRouteImport.update({
  id: '/loan',
  path: '/loan',
  getParentRoute: () => rootRouteImport,
} as any)
const MortgageRoute = MortgageRouteImport.update({
  id: '/mortgage',
  path: '/mortgage',
  getParentRoute: () => rootRouteImport,
} as any)
const PercentageRoute = PercentageRouteImport.update({
  id: '/percentage',
  path: '/percentage',
  getParentRoute: () => rootRouteImport,
} as any)
const ScientificRoute = ScientificRouteImport.update({
  id: '/scientific',
  path: '/scientific',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeDurationRoute = TimeDurationRouteImport.update({
  id: '/time-duration',
  path: '/time-duration',
  getParentRoute: () => rootRouteImport,
} as any)
const TipRoute = TipRouteImport.update({
  id: '/tip',
  path: '/tip',
  getParentRoute: () => rootRouteImport,
} as any)
const UnitConverterRoute = UnitConverterRouteImport.update({
  id: '/unit-converter',
  path: '/unit-converter',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/age': typeof AgeRoute
  '/basic': typeof BasicRoute
  '/bmi': typeof BmiRoute
  '/date': typeof DateRoute
  '/loan': typeof LoanRoute
  '/mortgage': typeof MortgageRoute
  '/percentage': typeof PercentageRoute
  '/scientific': typeof ScientificRoute
  '/time-duration': typeof TimeDurationRoute
  '/tip': typeof TipRoute
  '/unit-converter': typeof UnitConverterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/age': typeof AgeRoute
  '/basic': typeof BasicRoute
  '/bmi': typeof BmiRoute
  '/date': typeof DateRoute
  '/loan': typeof LoanRoute
  '/mortgage': typeof MortgageRoute
  '/percentage': typeof PercentageRoute
  '/scientific': typeof ScientificRoute
  '/time-duration': typeof TimeDurationRoute
  '/tip': typeof TipRoute
  '/unit-converter': typeof UnitConverterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/age': typeof AgeRoute
  '/basic': typeof BasicRoute
  '/bmi': typeof BmiRoute
  '/date': typeof DateRoute
  '/loan': typeof LoanRoute
  '/mortgage': typeof MortgageRoute
  '/percentage': typeof PercentageRoute
  '/scientific': typeof ScientificRoute
  '/time-duration': typeof TimeDurationRoute
  '/tip': typeof TipRoute
  '/unit-converter': typeof UnitConverterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/age'
    | '/basic'
    | '/bmi'
    | '/date'
    | '/loan'
    | '/mortgage'
    | '/percentage'
    | '/scientific'
    | '/time-duration'
    | '/tip'
    | '/unit-converter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/age'
    | '/basic'
    | '/bmi'
    | '/date'
    | '/loan'
    | '/mortgage'
    | '/percentage'
    | '/scientific'
    | '/time-duration'
    | '/tip'
    | '/unit-converter'
  id:
    | '__root__'
    | '/'
    | '/age'
    | '/basic'
    | '/bmi'
    | '/date'
    | '/loan'
    | '/mortgage'
    | '/percentage'
    | '/scientific'
    | '/time-duration'
    | '/tip'
    | '/unit-converter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgeRoute: typeof AgeRoute
  BasicRoute: typeof BasicRoute
  BmiRoute: typeof BmiRoute
  DateRoute: typeof DateRoute
  LoanRoute: typeof LoanRoute
  MortgageRoute: typeof MortgageRoute
  PercentageRoute: typeof PercentageRoute
  ScientificRoute: typeof ScientificRoute
  TimeDurationRoute: typeof TimeDurationRoute
  TipRoute: typeof TipRoute
  UnitConverterRoute: typeof UnitConverterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/age': {
      id: '/age'
      path: '/age'
      fullPath: '/age'
      preLoaderRoute: typeof AgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basic': {
      id: '/basic'
      path: '/basic'
      fullPath: '/basic'
      preLoaderRoute: typeof BasicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bmi': {
      id: '/bmi'
      path: '/bmi'
      fullPath: '/bmi'
      preLoaderRoute: typeof BmiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/date': {
      id: '/date'
      path: '/date'
      fullPath: '/date'
      preLoaderRoute: typeof DateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan': {
      id: '/loan'
      path: '/loan'
      fullPath: '/loan'
      preLoaderRoute: typeof LoanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mortgage': {
      id: '/mortgage'
      path: '/mortgage'
      fullPath: '/mortgage'
      preLoaderRoute: typeof MortgageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/percentage': {
      id: '/percentage'
      path: '/percentage'
      fullPath: '/percentage'
      preLoaderRoute: typeof PercentageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scientific': {
      id: '/scientific'
      path: '/scientific'
      fullPath: '/scientific'
      preLoaderRoute: typeof ScientificRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time-duration': {
      id: '/time-duration'
      path: '/time-duration'
      fullPath: '/time-duration'
      preLoaderRoute: typeof TimeDurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tip': {
      id: '/tip'
      path: '/tip'
      fullPath: '/tip'
      preLoaderRoute: typeof TipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unit-converter': {
      id: '/unit-converter'
      path: '/unit-converter'
      fullPath: '/unit-converter'
      preLoaderRoute: typeof UnitConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgeRoute: AgeRoute,
  BasicRoute: BasicRoute,
  BmiRoute: BmiRoute,
  DateRoute: DateRoute,
  LoanRoute: LoanRoute,
  MortgageRoute: MortgageRoute,
  PercentageRoute: PercentageRoute,
  ScientificRoute: ScientificRoute,
  TimeDurationRoute: TimeDurationRoute,
  TipRoute: TipRoute,
  UnitConverterRoute: UnitConverterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
